env:
    global:
        # GRADLE_PUBLISH_KEY
        - secure: Keb5d7edNmq3jeFg84MEG8TqhUutQqlIb5sU3pAGFvO0fkAW4NellvBI0iYbO9pF8/lkOVyr+kgDKD5ttDI6icjAEQ/07i8Lo0gLdmfPbwyhztJ2wXlfPxsMoxDdrFqrrpDU1HenfJPsMTf9qgImC7JEKyMp0imA6HB+DFp7pKVsOV8T7KLiFVR+oA0wUUN8V8LIaOTbF7FnehcF/XhzUk5HC5YthWT9RBBUIZn79GQ6dZ7+O3Fd1wJ5mgfX4ZxJRqVjOtmGPTlv0A1ngMEp4dWiqw0RA4iLgan1SIEtHmeuTytbWN2xAbE6ueTJ2QtFcyzKSpqCGuBe8U6rWbnvtfAwhLyq95OOwbsRdNjAjObMBVqLjQhuRDffODlu9mYMFyzDMecRapTagzpRMnxwqdyzPrEYDF280zQbtnHi+MB/P6zQpQl4aBGXYMo78c0rSjvqMlzb3XrKJS3b9uTrXCdnjzQ3CzezDXfekdd6lFevRq2jJYz2FezMX1lmHPpoQVyuvodMEXoomu0OKttrTLuwEc9dgWenHmz7gQ55KyzC469y1Mai7+RbMX3lGgqVKYdnTqURgNsLHnbAuV2YyGRJ5UtfB1NZNpBHbfLvRCX3ss3j4AV22UWxJOqTNn5JFXYwA5+mPmLGrFY87A0TH9QA62hyJGw/LObcZI9JSzI=
        # GRADLE_PUBLISH_SECRET
        - secure: v/q2iOeaNbzzCSLr7K8Wvt61pdevWUOGjRP0UHBXAJTe2Ji5VQTs05srzgZO3mtkWvDP0ieKL+Vz0rDy3Ww+PgodJV7SXcQ0ZDq4f+9syZ9VXoeW/5a/K5yvWWF6YxqHVm5wujOscq9RQbTF8zQlBKXaVmZjOV4zcBoN3etCb0sOZDK3ixuiI8XSVovI7CYorGXThd+qCJmjagJ8EO/Lr9CQaaDZILZTitm4RWUnVRkpSy2EGUtlVOYxmKhS3kSQxJtBS6o//waeUyXJLBRDAIeF2+MR4QRoVyLa2oZCvILNTD7VZb29jpoH/Ak6qipgagXq2U/vfaxc0naE95oOuD+vjDQfO75Nfq+etgaGQmriMYSmI/XTMoIwcQTAuFKpWf0FFrIMLWqoamRXR0whTlYfW8XWMk0UGoh0LOONi4zBSmZg8ZXwtPoWAZvUM+bY2VuP2zJCpOyzmHRyClGUSnzni+30Hj8DtFwXJ3yk3EJU9MQ/IF2x5LlbmkBs/TVvEhp4vPYTwRxfIjiBblsfPrU2wh84ZCdCZ4HQhAfT8OpN5jEKK6facaT4pln31kX5jFCTUn8Dq1p8iMDToKsV3I7NgVl5fjEFUTz+uRihcZwBjvx4AWoNrsMJyDrDYyDVBC4ygh+QqNtnUNh75fuek8EAelK4HPH83G/ZkMOvtaU=
        - GRADLE_OPTS="-Dorg.gradle.console=plain -Dgradle.publish.key='$GRADLE_PUBLISH_KEY' -Dgradle.publish.secret='$GRADLE_PUBLISH_SECRET'"
language: java
install: true
jobs:
  include:
    - stage: Build and Test
      script: ./gradlew -p android-emulator-plugin # Build and validate fully
      # Run all validations separately to speed up the build and avoid timeouts due to long builds.
    - script: ./validate_plugin 1
    - script: ./validate_plugin 2
    - script: ./validate_plugin 3
    - script: ./validate_plugin 4
    - script: ./validate_plugin 5
    - stage: Deploy
      script: skip
      deploy:
        provider: script
        script: ./gradlew -p android-emulator-plugin publishPlugins
        on:
          branch: master
          tags: true
