version: 2.1
orbs:
  circleci-github-cli: circleci/github-cli@2.0.0
workflows:
  Build and Test Workflow:
    jobs:
      - Build and Test:
          name: smoketest
          java: 8
          test_suite: 1
          filters:
            tags:
              only: /.*/
      - Build and Test:
          requires:
            - smoketest
          java: 11
          matrix:
            parameters:
              test_suite:
                - 2
                - 3
                # - 4 # Currently broken
                - 5
                - 6
                - 7
                - 8
                - 9
                - 10
          filters:
            tags:
              only: /.*/
      - Deploy:
          requires:
            - Build and Test
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

      - Dependabot Auto-Merge:
          context: github-cli
          requires:
            - smoketest
          filters:
            branches:
              only: /dependabot\/.*/

jobs:
  Build and Test:
    description: Build and Test - JDK << parameters.java >> - Test Suite << parameters.test_suite >>
    parameters:
      java:
        type: integer
      test_suite:
        type: integer
    machine:
      image: cimg/android:2022.1.1
    resource_class: medium
    environment:
      GRADLE_OPTS: -Dorg.gradle.console=plain -Dorg.gradle.jvmargs=-XX:MaxMetaspaceSize=512m
      ADB_INSTALL_TIMEOUT: 3
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install openjdk-<< parameters.java >>-jdk
      - run: java -version
      - run: ./gradlew -p android-emulator-plugin
      - store_test_results:
          path: android-emulator-plugin/build/reports
      - run: ./validate_plugin << parameters.test_suite >>
      - store_test_results:
          path: example-android-project/build/reports
  Deploy:
    description: Deploy the plugin
    machine:
      image: cimg/android:2022.1.1
    environment:
      GRADLE_OPTS: -Dorg.gradle.console=plain -Dorg.gradle.jvmargs=-XX:MaxMetaspaceSize=512m
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install openjdk-8-jdk
      - run: java -version
      - run: ./gradlew -p android-emulator-plugin publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
  Dependabot Auto-Merge:
    docker:
      - image: cimg/base:2022.02
    steps:
      - checkout
      - circleci-github-cli/install
      - run: |
          PR_AUTHOR="$(gh pr view $CIRCLE_PULL_REQUEST --json author --jq .author.login)"
          if [ "$PR_AUTHOR" != "dependabot" ]; then
            message='Invalid PR author, rejecting';
            echo "$message"
            gh pr review $CIRCLE_PULL_REQUEST --comment --body "$message"
            exit 1;
          else
            gh pr review $CIRCLE_PULL_REQUEST --comment --body "[Bot] Confirmed dependabot identity. @dependabot merge"
            gh pr review $CIRCLE_PULL_REQUEST --approve
          fi
